CREATE TABLE TBL_TEACHER_202201(
   TEACHER_CODE CHAR(3),
   TEACHER_NAME VARCHAR2(15),
   CLASS_NAME VARCHAR2(20),
   CLASS_PRICE NUMBER(8),
   TEACH_RESIST_DATE VARCHAR2(8),
   PRIMARY KEY(TEACHER_CODE)
);
